### ISSUE TITLE
Nice collection of rules and examples

### ISSUE THREAD

**Issue by springcoil** [ianozsvald/example_conversion_of_excel_to_pandas#1]
Hi Ian,
A nice collection of rules and examples of using Excel and converting to Pandas. 

The string application is a really useful one, I know numerous times I've seen similar examples in industry, like voda-fone, vodafone, Vodafone etc. 

Have you an experience of turning such rules into say a pipeline. Like 'survey data comes in with misspells and all' -> 'cleanish data'?

**Comment by ianozsvald** [comment]
Hey there. No experience of turning rules into a pipeline, not with Excel sheets.
